---
- name: Ensure Docker systemd directory is present.
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755
    owner: root
    group: root
    recurse: yes

- name: Enable Docker tcp and unix connections.
  copy:
    src: override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf
  notify: restart docker

- name: Force systemd to reread configs.
  systemd: daemon_reload=yes
