---
- name: Ensure GitLab Container is running.
  docker_container:
    name: turnkey_gitlab
    image: 192.168.1.162:8082/gitlab/gitlab-ce
    published_ports:
    - 8002:80
    state: started
    restart_policy: always
