---
- name: Ensure GitLab Container is running.
  docker_container:
    name: turnkey_gitlab
    image: gitlab/gitlab-ce
    published_ports:
    - 8002:80
    state: started
    restart_policy: always
